---
packages:
    - wget
    - curl
    - hwloc-devel
    - rdma-core-devel
    - lua-devel
    - munge-devel
    - pam-devel
    - readline-devel
    - numactl-devel
    - rrdtool-devel
    - ncurses-devel
    - gtk2-devel
    - gtk3-devel
   # - nvml-tools
    - pmix
    - libyaml-devel
    - json-c-devel
    - json-glib-devel
    - http-parser
    - bzip2
    - zlib
    - pkgconf-pkg-config
