- name: create netbox database
  postgresql_db:
    login_user: postgres
    name: "{{ db_name }}"

- name: create postgresql user
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: ALL