---
# tasks file for mariadb

# Add MariaDB repositories to all servers
- name: enable mariadb repository
  copy:
    dest: /etc/yum.repos.d/mariadb.repo
    content : |
      [mariadb]
      name = MariaDB
      baseurl = http://yum.mariadb.org/10.4/centos7-amd64
      gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck=1

# Install MariaDB on all servers
- name: install the mariadb server and client packages
  yum:
    name: 
      - MariaDB-server
      - MariaDB-client
      - rsync
      - policycoreutils-python
    state: present

- name: install mysql python packages
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'

# Start the MariaDB service and enable it
- name: ensure mariadb is started and enabled
  service: name=mariadb state=started enabled=yes

# Set MariaDB root password, remove anonymous users and remove test database
- name: set mariadb root user password
  mysql_user: user=root password={{ mysql_root_password }} host=localhost

- name: remove anonymous users
  mysql_user: user="" state=absent

- name: remove the test database
  mysql_db: name=test state=absent

- name: open MariaDB firewall ports
  firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled

- name: open Galera cluster firewall ports
  firewalld:
    port: 4567/tcp
    permanent: true
    state: enabled

- name: open incremental state transfers firewall ports
  firewalld:
    port: 4568/tcp
    permanent: true
    state: enabled

- name: open state snapshot transfers firewall ports
  firewalld:
    port: 4444/tcp
    permanent: true
    state: enabled

- name: add server to public zone
  firewalld:
    source: 10.1.10.69/32
    zone: public
    state: enabled
    permanent: true