---
splunk_forwarder_user: "splunk"
splunk_forwarder_group: "splunk"
splunk_forwarder_uid: "10011"
splunk_forwarder_gid: "10011"
splunk_release: "7.3.0"
splunk_url: "https://download.splunk.com/products/universalforwarder/releases/{{ splunk_release }}/linux"
splunk_forwarder_rpm: "splunkforwarder-7.3.0-657388c7a488-linux-2.6-x86_64.rpm"
splunk_rpm: "{{ splunk_url }}/{{ splunk_forwarder_rpm }}"
splunk_deb: "{{ splunk_url }}/{{ splunk_forwarder_deb }}"
splunk_deb_checksum: "md5:6d6a66e8040fe6ab04ad50615d26f93a"
splunk_rpm_checksum: "md5:3d14083431a8b62fac2205fe5dbe4586"


# These may be removed at some point, but they are placeholders so I don't forget to set them
splunk_forwarder_indexer: "10.1.10.22:9997"
splunk_forwarder_index: "default"
splunk_forwarder_sourcetype: "log"

splunk_forwarder_logs: |
  [monitor:///var/log/*]
