- name: install nginx package
  yum:
    name: nginx
    state: present
  tags: ['nginx','install']
    
- name: enable http traffic through firewall
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
  tags: ['nginx','firewall']

- name: enable https traffic through firewall
  firewalld:
    service: https
    state: enabled
    permanent: yes
    immediate: yes
  tags: ['nginx','firewall']

- name: change contents of index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html/
  tags: ['change-index']
  notify: restart nginx

- name: add kickstart file to html directory
  copy:
    src: ks.cfg
    dest: /usr/share/nginx/html
  tags: ['ngnix','kickstart']

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

