---
- hosts: all
  become: true
  tasks:
    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-Base.repo
        state: absent

    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-CR.repo
        state: absent

    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-Debuginfo.repo
        state: absent

    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-fasttrack.repo
        state: absent

    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-Media.repo
        state: absent

    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-Sources.repo
        state: absent

    - name: remove default repos
      file:
        path: /etc/yum.repos.d/CentOS-Vault.repo
        state: absent

    - name: copy new repo file
      copy:
        src: ../repofiles/lco-repos.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: '0644'