---
- hosts: all
  become: true
  tasks:
    - name: add specific node content to galera configuration file
      blockinfile:
        path: /etc/my.cnf.d/galera.cnf
        block: |
          [mysqld]
          binlog_format=ROW
          default-storage-engine=innodb
          innodb_autoinc_lock_mode=2
          bind-address=0.0.0.0

          # Galera Provider Configuration
          wsrep_on=ON
          wsrep_provider=/usr/lib64/galera-4/libgalera_smm.so

          # Galera Cluster Configuration
          wsrep_cluster_name="lco_cluster"
          wsrep_cluster_address="gcomm://10.1.10.67,10.1.10.68,10.1.10.69"

          # Galera Synchronization Configuration
          wsrep_sst_method=rsync

          # Galera Node Configuration
          wsrep_node_address="10.1.10.69"
          wsrep_node_name="dbcl3"