---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: get software for apt repository management
      apt:
        name:
          - python-apt
          - python-pycurl
        state: present
  
    - name: add ondrej repository for later versions of php
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: install apache, mysql, php and other dependencies
      apt: 
        name:
          - git
          - curl
          - unzip
          - sendmail
          - apache2
          - php7.1-common
          - php7.1-cli
          - php7.1-dev
          - php7.1-gd
          - php7.1-curl
          - php7.1-json
          - php7.1-opcache
          - php7.1-xml
          - php7.1-mbstring
          - php7.1-pdo
          - php7.1-mysql
          - php-apcu
          - libpcre3-dev
          - libapache2-mod-php7.1
          - python-mysqldb
          - mysql-server
        state: present

    - name: disable the firewall (for testing purposes only)
      service: name=ufw state=stopped

    - name: start apache, mysql, and php
      service: name={{ item }} state=started enabled=yes
      with_items:
        - apache2
        - mysql

    - name: enable apache rewrite module (required for Drupal)
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: add apache virtualhost for drupal 8 development
      template:
        src: "templates/drupal.test.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: symlink drupal virtualhost to sites-enabled.
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.test.conf"
        state: link
      notify: restart apache

    - name: remove default virtualhost file
      file:
        path: "/etc/apache2/sites-enabled/000-default.conf"
        state: absent
      notify: restart apache

    - name: adjust opcache memory setting
      lineinfile:
        dest: "/etc/php/7.1/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache

    - name: remove the MySQL test database
      mysql_db: db=test state=absent

    - name: create a database for drupal
      mysql_db: db={{ domain }} state=present

    - name: create a MySQL user for drupal
      mysql_user:
        name: "{{ domain }}"
        password: "1234"
        priv: "{{ domain }}.*:ALL"
        host: localhost
        state: present
