---
- hosts: ubuntu_lb
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: ubuntu_web
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

- hosts: ubuntu_db
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 state=started

- hosts: ubuntu_web
  become: true
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80

- hosts: ubuntu_lb
  become: true
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80