---
- hosts: ubuntu_lb
  become: true
  tasks:
    - name: verify nginx service
      command: systemctl status nginx
      changed_when: false
    
    - name: verify nginx is listening on port 80
      wait_for: port=80 timeout=1

- hosts: ubuntu_web
  become: true
  tasks:
    - name: verify apache service
      command: systemctl status apache2
      changed_when: false

    - name: verify apache2 is listening on port 80
      wait_for: port=80 timeout=1

- hosts: ubuntu_db
  become: true
  tasks:
    - name: verify mysql service
      command: systemctl status mysql
      changed_when: false

    - name: verify mysql is listening on port 3306
      wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=1

