- name: install nginx package
  yum:
    name: nginx
    state: present
    
- name: enable http traffic through firewall
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes

- name: enable https traffic through firewall
  firewalld:
    service: https
    state: enabled
    permanent: yes
    immediate: yes

- name: change contents of index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html/
  tags: ['change-index']
  notify: restart nginx

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

