---
# tasks file for jenkins
- name: install java jdk
  yum:
    name: java-1.8.0-openjdk-devel
    state: present

- name: enable jenkins repository
  copy:
    dest: /etc/yum.repos.d/jenkins.repo
    content: |
      [jenkins]
      name=Jenkins-stable
      baseurl=http://pkg.jenkins.io/redhat-stable
      gpgcheck=1 

- name: add the repository to the system
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins package
  yum:
    name: jenkins
    state: present

- name: ensure jenkins is running and enabled
  service:
    name: jenkins
    state: started
    enabled: yes

- name: ensure port 8080 is open on firewall
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: load azure credentials plugin
  copy:
    src: azure-credentials.hpi
    dest: /var/lib/jenkins/plugins
  notify: restart jenkins

- name: load azure cli plugin
  copy:
    src: azure-cli.hpi
    dest: /var/lib/jenkins/plugins
  notify: restart jenkins