---
- name: Download the Splunk package (CentOS)
  get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_forwarder_rpm }}"
    checksum: "{{ splunk_rpm_checksum }}"
  when: ansible_os_family == "RedHat"

- name: Install Splunk (CentOS)
  yum:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy inputs file
  template:
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    backup: yes
  tags: config_copy

- name: Copy outputs file
  template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    backup: yes
  tags: config_copy

- name: Upload Splunk Systemd Script
  copy:
    src: splunk.service
    dest: /etc/systemd/system/splunkd.service
    owner: 0
    group: 0
    mode: 0755
  notify: Enable Splunk Forwarder
  when: ansible_service_mgr == 'systemd'
