---
- hosts: all
  become: true
  tasks:
    - name: add ius centos 7 repo
      yum: name="https://centos7.iuscommunity.org/ius-release.rpm" state=present

    - name: install dependency packages
      yum:
        name:
          - python36
          - python36-devel
          - python36-setuptools
          - libxml2-devel
          - libxslt-devel
          - libffi-devel
          - openssl-devel
          - redhat-rpm-config
        state: present

    - name: install pip3
      command: easy_install-3.6 pip

    - name: install modules needed for netbox
      pip:
        name: pynetbox
        executable: /usr/local/bin/pip3