---
- hosts: vmrepo6
  become: true
  vars:
      rhel6_repos:
          - rhel-6-server-els-optional-rpms
          - rhel-6-server-els-rpms
          - rhel-6-server-rpms
  tasks:
      - name: reposync rhel6 repos
        command: reposync -p /fs/nfs_share --download-metadata --repo="{{ item }}" -n
        tags: ['repo6']
        loop: "{{ rhel6_repos }}"
  
- hosts: vmrepo8
  become: true
  vars:
      rhel8_repos:
          - rhel-8-for-x86_64-appstream-rpms
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-supplementary-rpms
          - JHUAPL_EPEL_8_EPEL_8
  tasks:
      - name: reposync rhel8 repos
        command: reposync -p /fs/nfs_share --download-metadata --repo="{{ item }}" -n
        tags: ['repo8']
        loop: "{{ rhel8_repos }}"
