---
- hosts: all
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: open httpd port on firewall
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
