- name: create database
  mysql_db: 
    name: "{{ db_name }}" 
    state: present

- name: create user
  mysql_user: 
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}" 
    priv: "'{{ db_name }}'.*:ALL" 
    host: "{{ db_user_host }}" 
    state: present
