- name: install java jdk
  yum:
    name: java-11-openjdk-devel.x86_64
    state: latest
  tags: ['java', 'start']

- name: install epel repository
  yum: name=epel-release state=present
  tags: ['gitupgrade']

- name: install endpoint repository
  yum:
    name: https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
    state: present
  when: ansible_distribution_major_version == "7"
  tags: ['gitupgrade']

- name: install git version > 2
  yum:
    name: git
    state: latest
  tags: ['gitupgrade']

- name: enable bitbucket firewall rules
  firewalld:
    port: 7990-7993/tcp
    permanent: yes
    state: enabled
    immediate: yes
  tags: ['bitbucket','firewall','start']

- name: create atlassian install directory
  file:
    path: /opt/atlassian
    state: directory
    mode: '0755'
    recurse: yes
  tags: ['start']

- name: create bitbucket home directory
  file:
    path: /opt/atlassian/bitbucket-home
    state: directory
    mode: '0755'
  tags: ['start']

- name: extract atlassian-bitbucket.tar.gz at /opt/atlassian
  unarchive:
    src: "{{ atlassian_bitbucket_path }}"
    dest: /opt/atlassian
    remote_src: yes
  tags: ['extract','start']

- name: set bitbucket home
  lineinfile:
    path: /opt/atlassian/atlassian-bitbucket-7.3.1/bin/set-bitbucket-home.sh
    regexp: "    BITBUCKET_HOME=$"
    line: "    BITBUCKET_HOME=/opt/atlassian/bitbucket-home"
  tags: ['bitbuckethome','start']

- name: set jre home
  lineinfile:
    path: /opt/atlassian/atlassian-bitbucket-7.3.1/bin/set-jre-home.sh
    regexp: "    JRE_HOME=$"
    line: "\tJRE_HOME=/usr/lib/jvm/jre-11-openjdk"
  tags: ['jrehome']

- name: create bitbucket systemd service
  copy:
    src: bitbucket.service
    dest: /etc/systemd/system/bitbucket.service
    mode: '0664'
  tags: ['start']

- name: reload daemon
  command: systemctl daemon-reload
  tags: ['start']

- name: start and enable bitbucket service
  service:
    name: bitbucket
    state: started
    enabled: yes
