- name: install epel repository
  yum: name=epel-release state=present

- name: install dependency packages
  yum:
    name:
      - python-psycopg2
    state: present
  tags:
    - deps

- name: install postgresql repository
  yum: 
    name: "https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm"
    state: present

- name: install postgresql packages
  yum:
    name:
      - postgresql96
      - postgresql96-server
      - postgresql96-devel

# Should only run once
- name: initialize postgresql database
  command: "/usr/pgsql-9.6/bin/postgresql96-setup initdb"
  tags: ['initdb']

- name: copy pg_hba.conf file
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgresql  

- name: copy postgresql.conf file
  copy:
    src: postgresql.conf
    dest: /var/lib/pgsql/9.6/data/
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgresql

- name: open postgresql firewall port
  firewalld:
    port: 5432/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: ensure postgresql is started and enabled
  service: name=postgresql-9.6 state=started enabled=yes


