- name: install java jdk
  yum:
    name: java-11-openjdk-devel.x86_64
    state: latest
  tags: ['java']

- name: enable confluence firewall rules
  firewalld:
      port: 8090-8091/tcp
      permanent: yes
      state: enabled
      immediate: yes
  tags: ['firewall']

- name: create the atlassian installation directory
  file:
      path: /opt/atlassian
      state: directory
      mode: '0755'
      recurse: yes
  tags: ['installdir']

- name: create confluence home directory
  file:
      path: /opt/altassian/confluence-home
      state: directory
      mode: '0755'
  tags: ['homedir']

- name: extract atlassian-confluence.tar.gz into installation directory
  unarchive:
      src: "{{ atlassian_confluence_path }}"
      dest: /opt/atlassian
      remote_src: yes
  tags: ['extract']

- name: set confluence home
  lineinfile:
      path: /opt/atlassian/atlassian-confluence-7.4.1/confluence/WEB-INF/classes/confluence-init.properties
      regexp: '#confluence.home'
      line: 'confluence.home = /opt/atlassian/confluence-home'
  tags: ['confluencehome']

- name: create confluence systemd service
  copy:
      src: confluence.service
      dest: /etc/systemd/system/confluence.service
      mode: '0664'
  tags: ['svc']

- name: reload daemon
  command: systemctl daemon-reload

- name: start and enable confluence service
  service:
    name: confluence
    state: started
    enabled: yes
