- name: stop the postgresql database service
  service:
    name: postgresql-9.6
    state: stopped

- name: remove all the contents of data folder
  file:
    state: absent
    path: /var/lib/pgsql/9.6/data/

- name: recreate empty data folder with all required permissions
  file:
    path: /var/lib/pgsql/9.6/data
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: perform backup from primary db server
  command: pg_basebackup -U repuser -h 10.1.10.44 -w -D /var/lib/pgsql/9.6/data

- name: set file ownership, group and permissions to postgres
  file:
    path: /var/lib/pgsql/9.6/data
    owner: postgres
    group: postgres
    recurse: yes

- name: copy recovery file
  copy:
    src: recovery.conf
    dest: /var/lib/pgsql/9.6/data
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgresql

- name: start postgresql service again
  service:
    name: postgresql-9.6
    state: started
